apiVersion: v1
kind: ConfigMap
metadata:
  name: castai-pdb-controller-config
  namespace: castai-agent
data:
  FixPoorPDBs: "false"
  defaultMinAvailable: "1"
  exclusions: |
    - namespaceRegex: "^kube-system$"
      nameRegex: ""
      labels: {}
    - namespaceRegex: ""
      nameRegex: ".*-temp$"
      labels:
        app: "^db-.*"
        env: "staging|dev"
    - namespaceRegex: "monitoring"
      nameRegex: ""
      labels:
        role: "critical"
    - namespaceRegex: "^simple-test$"
      nameRegex: ""
      labels: {}
    - namespaceRegex: "^default$"
      nameRegex: ""
      labels: {}
  garbageCollectInterval: "2m"
  logInterval: "15m"
  pdbDumpInterval: "5m"
  pdbScanInterval: "2m"