apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castai-pdb-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-pdb-controller.labels" . | nindent 4 }}
data:
  {{- if .Values.config.defaultMinAvailable }}
  {{- $minAvailable := toString .Values.config.defaultMinAvailable }}
  {{- if and (ne $minAvailable "") (ne $minAvailable "null") (ne $minAvailable "<nil>") }}
  defaultMinAvailable: {{ .Values.config.defaultMinAvailable | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.config.defaultMaxUnavailable }}
  {{- $maxUnavailable := toString .Values.config.defaultMaxUnavailable }}
  {{- if and (ne $maxUnavailable "") (ne $maxUnavailable "null") (ne $maxUnavailable "<nil>") }}
  defaultMaxUnavailable: {{ .Values.config.defaultMaxUnavailable | quote }}
  {{- end }}
  {{- end }}
  FixPoorPDBs: {{ .Values.config.FixPoorPDBs | quote }}
  logInterval: {{ .Values.config.logInterval | quote }}
  pdbScanInterval: {{ .Values.config.pdbScanInterval | quote }}
  garbageCollectInterval: {{ .Values.config.garbageCollectInterval | quote }}
  pdbDumpInterval: {{ .Values.config.pdbDumpInterval | quote }} 