apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castai-pdb-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-pdb-controller.labels" . | nindent 4 }}
data:
  {{- if .Values.config.defaultMinAvailable }}
  defaultMinAvailable: {{ .Values.config.defaultMinAvailable | quote }}
  {{- end }}
  {{- if .Values.config.defaultMaxUnavailable }}
  defaultMaxUnavailable: {{ .Values.config.defaultMaxUnavailable | quote }}
  {{- end }}
  FixPoorPDBs: {{ .Values.config.FixPoorPDBs | quote }}
  logInterval: {{ .Values.config.logInterval | quote }}
  pdbScanInterval: {{ .Values.config.pdbScanInterval | quote }}
  garbageCollectInterval: {{ .Values.config.garbageCollectInterval | quote }}
  pdbDumpInterval: {{ .Values.config.pdbDumpInterval | quote }} 