# Default values for castai-pdb-controller
# Number of controller replicas to deploy
replicaCount: 2

# Container image configuration
image:
  # Container image repository
  repository: castai/castai-pdb-controller
  # Container image tag
  tag: "0.1"
  # Container image pull policy
  pullPolicy: IfNotPresent

# Name overrides for the chart
nameOverride: ""
fullnameOverride: ""

# ServiceAccount configuration
serviceAccount:
  # Create a new service account
  create: true
  # Service account name
  name: "castai-pdb-controller"
  # Service account annotations (useful for IAM roles, etc.)
  annotations: {}

# RBAC configuration
rbac:
  # Create RBAC resources (ClusterRole and ClusterRoleBinding)
  create: true

# Controller configuration
config:
  # Default minAvailable for PDBs (use either defaultMinAvailable or defaultMaxUnavailable, not both)
  # Set to null, "", or omit to disable minAvailable mode
  # Examples: "1", "50%", null, ""
  defaultMinAvailable: null
  # Default maxUnavailable for PDBs (use either defaultMinAvailable or defaultMaxUnavailable, not both)
  # Set to null, "", or omit to disable maxUnavailable mode
  # Examples: "1", "50%", null, ""
  defaultMaxUnavailable: null
  # Automatically fix poor PDB configurations (true/false)
  FixPoorPDBs: "false"    # Set to "true" for automatic correction, "false" for logging only
  # Log interval for repeated messages (e.g., "15m", "1h")
  logInterval: "15m"
  # PDB scan interval (e.g., "2m", "5m")
  pdbScanInterval: "2m"
  # Garbage collection interval (e.g., "2m", "5m")
  garbageCollectInterval: "2m"
  # PDB dump interval (e.g., "5m", "10m")
  pdbDumpInterval: "5m"

# Resource configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Security context configuration
securityContext:
  # Container security context
  container:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
  # Pod security context
  pod:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

# Pod configuration
pod:
  # Pod annotations
  annotations: {}
  # Node selector for pod assignment
  nodeSelector: {}
  # Tolerations for pod assignment
  tolerations: []
  # Affinity for pod assignment
  affinity: {}

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25% 